### ISSUE TITLE
Python's 'self' keyword not being properly highlighted

### ISSUE THREAD

**Issue by heyvito** [IanWold/MonokaiGray#2]
Hello there!
I really do enjoy this theme (have been using it since dec/2013), but there is a little annoying detail I considered important to report:

When writing in Python, `self` keywords are not properly highlighted, while when using Sublime's _built-in_ Monokai, they are. 

Is there any way to fix it? 

Thank you!

**Comment by IanWold** [comment]
That's very curious, indeed. I'll definitely look into that. Thanks for mentioning this!

**Comment by IanWold** [comment]
I am not able to reproduce this issue. I'm using the following snippet:

``` python
class Bank(): # let's create a bank, building ATMs
    crisis = False
    def create_atm(self) :
    while not self.crisis :
    yield "$100"
```

The behavior in Monokai and Monokai Gray seems to be the same for me: on line 3, the self keyword is highlighted. However, on line 4, the self keyword is not highlighted. 

Could you check with that code to see if that is the behavior you experience with both Monokai and Monokai Gray? If it is not, then there is either something different with the Python syntax definition or Monokai theme on your computer.

**Comment by heyvito** [comment]
Thank you for replying quickly!

Sorry for confusing a point:
MonokaiGray and Monokai behaves in the very same way: `def create_atm(self):` is highlighted for being a function argument (in a function signature), but `while not self.crisis:` does not.
I believe that `self` in `self.crisis` should be highlighted the same way as `while`, `yield` and `not` (as a keyword?), since in other color schemes it does happen (including here on GitHub! Check out your snippet and you can notice that all occurrences of `self` are highlighted)

Let me compare Monokai[Gray] with `base16-eighties.dark`, from the SpaceGray Eighties theme package:

Monokai:
![monokai](https://cloud.githubusercontent.com/assets/77198/3201754/00f426f4-ed8b-11e3-8392-9005607adbdc.png)

MonokaiGray:
![monokaigray](https://cloud.githubusercontent.com/assets/77198/3201733/d77dbcd6-ed8a-11e3-9417-0f188d9c0da8.png)

base16-eighties.dark:
![base16](https://cloud.githubusercontent.com/assets/77198/3201749/f5b36070-ed8a-11e3-8654-71f8e0e85e03.png)

I mean, by highlighting `self`, MonokaiGray will continue pleasant as it is, and will even get way better than the original Monokai.

Thank you, once again!

**Comment by IanWold** [comment]
Ah, very good! I see what you're saying now, thank you.

I went and found the code for base16-eighties.dark [here](https://raw.githubusercontent.com/kkga/spacegray/master/base16-eighties.dark.tmTheme), and at first glance, it seems significantly better written than Monokai was. I say that because everything is more organized and it seems like they're able to support more syntactical niceties, such as this self keyword, as a result.

I'll take a shot at it and see if I can work it out, it doesn't seem like so difficult a solution. I don't know how soon I'll be able to work this one out; I have a couple other projects that keep distracting me :smile: But I'll keep this issue open here.

**Comment by heyvito** [comment]
Perfect! If you don't mind I will try to find a way to update MonokaiGray to this better structure and open a PR.

**Comment by IanWold** [comment]
If you want to tackle this, that would be awesome! I look forward to seeing what you come up with.

**Comment by heyvito** [comment]
After checking out a diff, I noticed it changes your whole codebase and I do not think it is a good idea (Unless you say it is okay if I change everything).

Besides that, I will open a PR that fixes this `self` problem (and also keeps Ruby's `@` signs unhighlighted)

**Comment by IanWold** [comment]
Indeed, the two schemes are very differently written. I think what you've done here is great for now, and I think more niceties can be tackled in the future as they arise. Thank you much!

**Comment by heyvito** [comment]
You are welcome. :grinning:
