### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by ghost** [IanWold/MonokaiGray#4]
My sidebar doesn't turn black. It stays at the stock blueish gray. Any ideas?

**Comment by IanWold** [comment]
Because Monokai Gray is a color scheme, it only changes the colors of the text and the text editor area. If you want to change the color of the sidebar, you'll need to do that with the theme. Chances are you can probably edit your current theme to have a true-gray color.

**Comment by ghost** [comment]
Ah right. Cheers :)
